config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/foods", to: "foods#index", as: "food_index" 
  post "/foods", to: "foods#create", as: "food_create"
  get "/foods/new", to: "foods#new", as: "food_new"
  get "/foods/:id", to: "foods#show", as: "food_show"
  get "/foods/:id/edit", to: "foods#edit", as: "food_edit"
  put "/foods/:id", to: "foods#update", as: "food_update"
  delete "/foods/:id", to: "foods#destroy", as: "food_destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def index
        @foods = Food.all.order("id")
    end

    def new
        
    end

    def create
        new_food = Food.create(
            name: params["name"],
            calories: params["calories"].to_i
        )
        redirect_to food_index_path
    end


    def show
        @food = Food.find(params["id"])
    end

    
    def edit
        @food = Food.find(params["id"])
    end

    def update
        updated_food = Food.update(
            params["id"], 
            name: params["name"], 
            calories: params["calories"]
        )
        redirect_to food_index_path(params["id"])
    end

    def destroy
        @food = Food.find(params["id"])
        @food.destroy

        redirect_to food_index_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/edit.html.erb
<form action="/foods/<%= @food.id %>" method="POST">
    <%= render "shared/food_form", name_value:@food.name, calories_value:@food.calories %>
</form>

app/views/foods/index.html.erb
<h1>Food List</h1>
<button>
    <%= link_to 'Add Dish', food_new_path %>
</button>


<table>
    <%= render "shared/food_headrow"%>
    <% @foods.each do |food| %>
        <% id = food.id %>
        <% name = food.name %>
        <% calories = food.calories %>
        <%= render "shared/food_row", id:id, name:name, calories:calories %>
    <% end %>
</table>

app/views/foods/new.html.erb
<form action="<%= food_create_path %>" method="POST">
    <%= render "shared/food_form" %>
</form>

app/views/foods/show.html.erb
<h1>Dish</h1>
<table>
    <%= render "shared/food_headrow"%>
    <% id = @food.id %>
    <% name = @food.name %>
    <% calories = @food.calories %>
    <%= render "shared/food_row", id:id, name:name, calories:calories %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foods</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_food_form.html.erb
<input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />

    <input type="hidden" name="_method" value="put" />

    <label for="name">Dish Name:</label><input type="text" name="name" value="<%= defined?(name_value)? name_value : "Dish name" %>" />
    <br>
    <label for="calories">Calories:</label><input type="number" name="calories" value="<%= defined?(calories_value)? calories_value : 0 %>" />
    <br>
    <button type="submit">Submit</button>

app/views/shared/_food_headrow.html.erb
<tr>
    <th>
        
    </th>
    <th>
        Dish Name
    </th>
    <th>
        Calories
    </th>
    
</tr>

app/views/shared/_food_row.html.erb
<tr>
    <td class="number">
        <%= id %>
    </td>
    <td>
        <%= name %>
    </td>
    <td class="number">
        <%= calories %>
    </td>
    <td>
        <button><%= link_to 'Edit', food_edit_path(id) %></button>
    
    <td>
        <button><%= link_to 'X', food_destroy_path(id), method: :delete %></button>
    </td>
</tr>